name: Build and Test Python Application (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Нужно для загрузки артефактов

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r win/requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 win/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 win/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pip install pytest
        pytest win/tests/ --maxfail=1 --disable-warnings -q

    - name: Build executable with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile --name cloudflare-tunnel.exe win/app.py

    - name: Upload artifact (Windows Executable)
      uses: actions/upload-artifact@v3
      with:
        name: cloudflare-tunnel-windows
        path: dist/cloudflare-tunnel.exe  # Путь к собранному exe
